const pdfDocument = require('pdfkit');
const dbconnection = require('../config/stylesConnection');
const path = require("path")

exports.customerDetails = (req, res) => {
  const customerId = req.params.customerId;

  const sql = 'CALL getEditCustomer(?)';

  dbconnection.query(sql, [customerId], (err, result) => {
    if (err) {
      console.log(err);
      return res.status(500).json({ message: 'Database Error' });
    }

    const customerData = result[0][0];

    const DOB = customerData.customerDOB;
    const DOBobj = new Date(DOB);
    const cleanDate = DOBobj.toLocaleDateString();
    console.log(customerData.customerImage)

    const document = new pdfDocument({ size: 'A4', margin: 40 });

    res.setHeader('Content-Type', 'application/pdf');

    res.setHeader('Content-Disposition', `inline; filename=${customerId}-${customerData.customerName}.pdf`);

    document.pipe(res);

    /* BACKGROUND */

    document.rect(0,0,612,792).fill('#f4f7fb');

    /* MAIN CARD */

    document.roundedRect(40,70,530,400,20).fillAndStroke('#ffffff','#dbeafe');

    /* LEFT IMAGE CARD */

    document.roundedRect(65,95,230,350,18).fillAndStroke('#eef2ff','#c7d2fe');

    /* RIGHT DETAILS CARD */

    document.roundedRect(315,95,220,350,18).fillAndStroke('#f8fafc','#e2e8f0');

    /* IMAGE */

    const imagePath = path.join(__dirname,'..','uploads','media',customerData.customerImage);

    document.image(imagePath,82,110,{width:195,height:255});

    /* TITLE */

    document.fontSize(22).fillColor('#2563eb').font('Helvetica-Bold').text('Customer Profile',315,120,{width:220,align:'center'});

    /* SUBTITLE */

    document.fontSize(10).fillColor('#64748b').font('Helvetica').text('Customer Information Details',315,150,{width:220,align:'center'});

    /* NAME */

    document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('FULL NAME',340,190);

    document.fontSize(16).fillColor('#111827').font('Helvetica').text(customerData.customerName,340,210);

    /* EMAIL */

    document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('EMAIL ADDRESS',340,245);

    document.fontSize(15).fillColor('#111827').font('Helvetica').text(customerData.customerEmail,340,265);

    /* MOBILE */

    document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('MOBILE NUMBER',340,300);

    document.fontSize(15).fillColor('#111827').font('Helvetica').text(customerData.customerMobile,340,320);

    /* DOB */

    document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('DATE OF BIRTH',340,355);

    document.fontSize(15).fillColor('#111827').font('Helvetica').text(cleanDate,340,375);

    /* CITY */

    document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('CITY',340,405);

    document.fontSize(15).fillColor('#111827').font('Helvetica').text(customerData.customerCity,340,425);

    /* FOOTER LINE */

    document.moveTo(90,470).lineTo(520,470).strokeColor('#cbd5e1').stroke();

    /* FOOTER */

    document.fontSize(10).fillColor('#94a3b8').font('Helvetica').text('Generated By Customer Management System',180,485);

    /* END */

    document.end();
  });
};
