const dbconnection = require('../config/stylesConnection');
const pdfkit = require('pdfkit')
const path = require("path");

exports.employeeDetails = (req,res)=> {

    const employeeId = req.params.employeeId;

    const sql = "SELECT * FROM employee where id = ?";

    dbconnection.query(sql,[employeeId],(err,result)=>{
        if(err){
            console.log(err);
            return res.status(500).json({err});
        }

        const employeeData = result[0];
        console.log(employeeData);

        /* PDF DOCUMENT */

        const document = new pdfkit({ size: 'A4', margin: 40 });

        /* RESPONSE */

        res.setHeader('Content-Type', 'application/pdf');

        res.setHeader('Content-Disposition', `inline; filename=${employeeData.firstname}-${employeeData.lastname}.pdf`);

        document.pipe(res);

        /* BACKGROUND */

        document.rect(0,0,612,792).fill('#f4f7fb');

        /* MAIN CARD */

        document.roundedRect(35,50,540,680,20).fillAndStroke('#ffffff','#dbeafe');

        /* LEFT IMAGE CARD */

        document.roundedRect(60,90,200,260,18).fillAndStroke('#eef2ff','#c7d2fe');

        /* RIGHT TOP CARD */

        document.roundedRect(285,90,250,260,18).fillAndStroke('#f8fafc','#e2e8f0');

        /* BOTTOM DETAILS CARD */

        document.roundedRect(60,380,475,300,18).fillAndStroke('#f8fafc','#e2e8f0');

        /* IMAGE */
        const imagePath = path.join(

        __dirname,

        '..',

        'uploads',

        'media',

        employeeData.image

        );
         document.image(imagePath,75,105,{width:170,height:230});

        /* TITLE */

        document.fontSize(24).fillColor('#2563eb').font('Helvetica-Bold').text('Employee Profile',285,110,{width:250,align:'center'});

        /* SUBTITLE */

        document.fontSize(10).fillColor('#64748b').font('Helvetica').text('Employee Information Details',285,145,{width:250,align:'center'});

        /* EMPLOYEE ID */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('EMPLOYEE ID',305,190);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.id,305,210);

        /* FULL NAME */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('FULL NAME',305,245);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(`${employeeData.firstname} ${employeeData.lastname}`,305,265);

        /* EMAIL */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('EMAIL ADDRESS',305,300);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.email,305,320);

        /* MOBILE */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('MOBILE NUMBER',70,410);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.mobile,70,430);

        /* ADDRESS */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('ADDRESS',70,470);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.address,70,490,{width:420});

        /* COUNTRY */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('COUNTRY',70,550);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.country,70,570);

        /* STATE */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('STATE',250,550);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.state,250,570);

        /* GENDER */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('GENDER',430,550);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.gender,430,570);

        /* HOBBIES */

        document.fontSize(11).fillColor('#2563eb').font('Helvetica-Bold').text('HOBBIES',70,620);

        document.fontSize(15).fillColor('#111827').font('Helvetica').text(employeeData.hobbies,70,640,{width:420});

        /* FOOTER LINE */

        document.moveTo(80,705).lineTo(530,705).strokeColor('#cbd5e1').stroke();

        /* FOOTER */

        document.fontSize(10).fillColor('#94a3b8').font('Helvetica').text('Generated By Employee Management System',170,715);

        /* END */

        document.end();
    })
}