const dbconnection = require("../config/stylesConnection");
const path = require("path");
const pdfkit = require("pdfkit");

exports.printEmployees = (req,res) => {
    const sql = 'CALL getEmployeesAll()';

    dbconnection.query(sql,(err,result)=>{
        if(err){
            console.log(err);
            return res.status(500).json({res});
        }

        const employeeData = result[0];
        console.log(employeeData);
        

        const document = new pdfkit;

        res.setHeader('Content-Type', 'application/pdf');

        res.setHeader('Content-Disposition', `inline; filename=ALL Employees.pdf`);

        document.pipe(res);
        
              /* BACKGROUND */
        
              document.rect(0,0,612,792).fill('#f8fafc');
        
              /* TITLE */
        
              document.fontSize(26).fillColor('#2563eb').font('Helvetica-Bold').text('Customer Invoice Report',40,40);
        
              document.fontSize(11).fillColor('#64748b').font('Helvetica').text('Customer Management System',40,75);
        
              /* START POSITION */
        
              let y = 120;
        
              let count = 0;
        
              /* LOOP */
        
              employeeData.forEach((employee,index)=>
                {
        
                /* NEW PAGE AFTER 5 */
        
                    if(count===5){
        
                    document.addPage();
        
                    document.rect(0,0,612,792).fill('#f8fafc');
        
                    document.fontSize(23).fillColor('#2563eb').font('Helvetica-Bold').text('Customer Invoice Report',40,40);
        
                    document.fontSize(11).fillColor('#64748b').font('Helvetica').text('Customer Management System',40,75);
        
                    y = 120;
        
                    count = 0;
        
                    }
        
                    /* CARD */

                    document.roundedRect(40,y,520,95,14).fillAndStroke('#ffffff','#dbeafe');

                    /* IMAGE BOX */

                    document.roundedRect(55,y+12,70,70,10).fillAndStroke('#eef2ff','#c7d2fe');

                    /* IMAGE */
                    if(employee.image){
                        
                        const imagePath = path.join(__dirname,'..','uploads','media',employee.image)

                        document.image(imagePath,63,y+20,{width:54,height:54});

                    }
                    /* COLUMN 1 */

                    document.fontSize(9).fillColor('#94a3b8').font('Helvetica-Bold').text('EMPLOYEE NAME',145,y+20);

                    document.fontSize(12).fillColor('#111827').font('Helvetica').text(`${employee.firstname} ${employee.lastname}`,145,y+35);

                    document.fontSize(9).fillColor('#94a3b8').font('Helvetica-Bold').text('MOBILE NUMBER',145,y+58);

                    document.fontSize(11).fillColor('#111827').font('Helvetica').text(employee.mobile,145,y+72);

                    /* COLUMN 2 */

                    document.fontSize(9).fillColor('#94a3b8').font('Helvetica-Bold').text('EMAIL ADDRESS',340,y+20);

                    document.fontSize(11).fillColor('#111827').font('Helvetica').text(employee.email,340,y+35,{width:180});

                    document.fontSize(9).fillColor('#94a3b8').font('Helvetica-Bold').text('LOCATION',340,y+58);

                    document.fontSize(11).fillColor('#111827').font('Helvetica').text(`${employee.state}, ${employee.country}`,340,y+72);

                    /* NEXT CARD POSITION */

                    y += 110;

                    count++;
                });
        
              /* FOOTER */
        
              document.fontSize(10).fillColor('#94a3b8').text('Generated By Customer Management System',180,740);
        
              /* END */
        
              document.end();

    })
}