const PDFDocument =  require('pdfkit');

const dbconnection = require('../config/stylesConnection');

const path = require("path");

exports.printCustomersDetails = (req,res)=>{

  const sql = "CALL getCustomers()";

  dbconnection.query( sql, (err,result)=>{

      if(err){

        return res.status(500).json({ message:'Database Error'});

      }

      const customers = result[0];

      const document = new PDFDocument({ size:'A4', margin:40 });

      /* RESPONSE */

      res.setHeader(

        'Content-Type',

        'application/pdf'

      );

      res.setHeader(

        'Content-Disposition',

        'inline; filename=CustomersReport.pdf'

      );

      document.pipe(res);

      /* BACKGROUND */

      document.rect(0,0,612,792).fill('#f8fafc');

      /* TITLE */

      document.fontSize(26).fillColor('#2563eb').font('Helvetica-Bold').text('Customer Invoice Report',40,40);

      document.fontSize(11).fillColor('#64748b').font('Helvetica').text('Customer Management System',40,75);

      /* START POSITION */

      let y = 120;

      let count = 0;

      /* LOOP */

      customers.forEach((customer,index)=>
        {

        /* NEW PAGE AFTER 5 */

            if(count===5){

            document.addPage();

            document.rect(0,0,612,792).fill('#f8fafc');

            document.fontSize(23).fillColor('#2563eb').font('Helvetica-Bold').text('Customer Invoice Report',40,40);

            document.fontSize(11).fillColor('#64748b').font('Helvetica').text('Customer Management System',40,75);

            y = 120;

            count = 0;

            }

            /* CARD */

            document.roundedRect(40,y,520,110,14).fillAndStroke('#ffffff','#dbeafe');

            /* IMAGE CARD */

            document.roundedRect(55,y+15,80,80,10).fillAndStroke('#eef2ff','#c7d2fe');

            /* IMAGE */

            const imagePath = path.join(__dirname,'..','uploads','media',customer.customerImage);

            document.image(imagePath,65,y+25,{width:60,height:60});

            /* COLUMN 1 → NAME + MOBILE */

            document.fontSize(11).fillColor('#94a3b8').font('Helvetica-Bold').text('FULL NAME',160,y+25);

            document.fontSize(15).fillColor('#111827').font('Helvetica').text(customer.customerName,160,y+42);

            document.fontSize(11).fillColor('#94a3b8').font('Helvetica-Bold').text('MOBILE NUMBER',160,y+70);

            document.fontSize(14).fillColor('#111827').font('Helvetica').text(customer.customerMobile,160,y+86);

            /* COLUMN 2 → EMAIL + CITY */

            document.fontSize(11).fillColor('#94a3b8').font('Helvetica-Bold').text('EMAIL ADDRESS',340,y+25);

            document.fontSize(14).fillColor('#111827').font('Helvetica').text(customer.customerEmail,340,y+42,{width:180});

            document.fontSize(11).fillColor('#94a3b8').font('Helvetica-Bold').text('CITY',340,y+70);

            document.fontSize(14).fillColor('#111827').font('Helvetica').text(customer.customerCity,340,y+86);

            /* NEXT POSITION */

            y += 125;

            count++;

        });

      /* FOOTER */

      document.fontSize(10).fillColor('#94a3b8').text('Generated By Customer Management System',180,740);

      /* END */

      document.end();

    }

  );

};